import type { JobOpening, Business, ServiceProvider, CommercialSpace, InvestorLead, JobApplication } from '@/types';

export const mockJobs: JobOpening[] = [
  { id:'job-001', title:'Community Center Manager', slug:'community-center-manager', description:'Lead the daily operations of the Lakefront Estates Community Center. Manage staff, coordinate events, oversee facility maintenance, and ensure a welcoming environment for all residents.', requirements:'5+ years management experience, event coordination, budget management', benefits:'Competitive salary, health insurance, paid time off, community housing discount', employerName:'Lakefront Estates Management', category:'Management', type:'full-time', workMode:'on-site', location:'Okeechobee, FL', salaryMin:55000, salaryMax:72000, salaryType:'annual', status:'published', isPublic:true, postedDate:'2026-03-10', applicationCount:12 },
  { id:'job-002', title:'Retail Store Associate', slug:'retail-store-associate', description:'Join our growing retail team at the Lakefront Shopping Plaza. Assist customers, manage inventory, process transactions, and help maintain store presentation.', requirements:'Customer service experience preferred, reliable transportation', benefits:'Flexible scheduling, employee discounts, growth opportunities', employerName:'Lakefront Shopping Plaza', category:'Retail', type:'part-time', workMode:'on-site', location:'Okeechobee, FL', salaryMin:15, salaryMax:18, salaryType:'hourly', status:'published', isPublic:true, postedDate:'2026-03-15', applicationCount:8 },
  { id:'job-003', title:'Medical Office Receptionist', slug:'medical-office-receptionist', description:'Front desk reception for the Lakefront Medical Center. Schedule appointments, manage patient records, handle insurance verification.', requirements:'Medical office experience, EMR proficiency, bilingual preferred', benefits:'Full benefits package, competitive pay, modern facility', employerName:'Lakefront Medical Center', category:'Healthcare', type:'full-time', workMode:'on-site', location:'Okeechobee, FL', salaryMin:38000, salaryMax:45000, salaryType:'annual', status:'published', isPublic:true, postedDate:'2026-03-08', applicationCount:15 },
  { id:'job-004', title:'Maintenance Technician', slug:'maintenance-technician', description:'Responsible for upkeep and maintenance of community facilities, residential common areas, and commercial properties.', requirements:'Trade certification preferred, HVAC experience a plus, valid FL drivers license', benefits:'Competitive hourly rate, overtime available, tool allowance', employerName:'Lakefront Property Management', category:'Maintenance', type:'full-time', workMode:'on-site', location:'Okeechobee, FL', salaryMin:20, salaryMax:28, salaryType:'hourly', status:'published', isPublic:true, postedDate:'2026-03-12', applicationCount:6 },
  { id:'job-005', title:'Marketing Coordinator', slug:'marketing-coordinator', description:'Drive awareness and engagement for Lakefront Economy. Create content, manage social media, coordinate events, develop marketing materials.', requirements:'Marketing degree or 3+ years experience, content creation, social media proficiency', benefits:'Hybrid work option, professional development budget, health benefits', employerName:'Lakefront Economy', category:'Marketing', type:'full-time', workMode:'hybrid', location:'Okeechobee, FL', salaryMin:42000, salaryMax:55000, salaryType:'annual', status:'published', isPublic:true, postedDate:'2026-03-05', applicationCount:22 },
  { id:'job-006', title:'Security Officer', slug:'security-officer', description:'Ensure the safety and security of Lakefront Estates community. Patrol grounds, monitor security systems, respond to incidents.', requirements:'Valid FL Class D Security License, clean background, first aid/CPR', benefits:'Shift differentials, benefits for full-time, training provided', employerName:'Lakefront Estates Security', category:'Security', type:'full-time', workMode:'on-site', location:'Okeechobee, FL', salaryMin:16, salaryMax:22, salaryType:'hourly', status:'published', isPublic:true, postedDate:'2026-03-01', applicationCount:9 },
];

// Essential businesses needed for the development — shows what's available vs taken
export interface BusinessOpportunity { id:string; name:string; category:string; description:string; status:'available'|'taken'|'coming-soon'; assignedTo?:string; icon:string; priority:'essential'|'high'|'medium'; }

export const businessOpportunities: BusinessOpportunity[] = [
  { id:'bop-001', name:'Grocery / Supermarket', category:'Food & Beverage', description:'Full-service grocery store with kosher selections, fresh produce, bakery, deli, and everyday essentials. The anchor store for the community.', status:'taken', assignedTo:'Lakefront Supermarket', icon:'ShoppingCart', priority:'essential' },
  { id:'bop-002', name:'Medical Center / Urgent Care', category:'Healthcare', description:'Primary care, urgent care, and basic medical services for the community and surrounding area.', status:'taken', assignedTo:'Lakefront Medical Center', icon:'Stethoscope', priority:'essential' },
  { id:'bop-003', name:'Pharmacy / Drugstore', category:'Healthcare', description:'Prescription pharmacy, over-the-counter medications, health supplies, and basic convenience items.', status:'available', icon:'Pill', priority:'essential' },
  { id:'bop-004', name:'Restaurant / Dining', category:'Food & Beverage', description:'Sit-down restaurant serving the community. Kosher dining preferred. Could include dairy or meat restaurant.', status:'available', icon:'UtensilsCrossed', priority:'essential' },
  { id:'bop-005', name:'Bakery / Cafe', category:'Food & Beverage', description:'Fresh baked goods, coffee, light meals. A community gathering spot.', status:'available', icon:'Coffee', priority:'high' },
  { id:'bop-006', name:'Dry Cleaner / Laundry', category:'Services', description:'Professional dry cleaning, laundry services, alterations, and tailoring for residents and businesses.', status:'available', icon:'Shirt', priority:'high' },
  { id:'bop-007', name:'Hardware / Home Improvement', category:'Retail', description:'Hardware store with tools, building materials, paint, plumbing, and electrical supplies for homeowners.', status:'available', icon:'Hammer', priority:'high' },
  { id:'bop-008', name:'Childcare / Daycare Center', category:'Education', description:'Licensed childcare facility for infants through pre-K. Essential for working families in the community.', status:'available', icon:'Baby', priority:'essential' },
  { id:'bop-009', name:'Gas Station / Auto Service', category:'Automotive', description:'Fuel station with basic auto services — oil changes, tire service, car wash.', status:'coming-soon', icon:'Fuel', priority:'high' },
  { id:'bop-010', name:'Bank / Credit Union Branch', category:'Financial', description:'Banking branch with ATM, personal banking, small business banking, and mortgage services.', status:'available', icon:'Landmark', priority:'essential' },
  { id:'bop-011', name:'Insurance Agency', category:'Financial', description:'Insurance office offering home, auto, life, and business insurance to community members.', status:'available', icon:'Shield', priority:'medium' },
  { id:'bop-012', name:'Accounting / Tax Office', category:'Professional', description:'CPA or tax preparation office serving individuals and small businesses in the development.', status:'available', icon:'Calculator', priority:'medium' },
  { id:'bop-013', name:'Law Office', category:'Professional', description:'Legal services — real estate, business, family law, estate planning for community members.', status:'available', icon:'Scale', priority:'medium' },
  { id:'bop-014', name:'Dental Office', category:'Healthcare', description:'General and family dentistry serving the community. Orthodontics a plus.', status:'available', icon:'Smile', priority:'high' },
  { id:'bop-015', name:'Clothing / Apparel Store', category:'Retail', description:'Mens, womens, and childrens clothing. Could specialize in modest/community-appropriate fashion.', status:'available', icon:'ShoppingBag', priority:'medium' },
  { id:'bop-016', name:'Pizza / Fast Casual', category:'Food & Beverage', description:'Quick-service restaurant — pizza, falafel, or similar casual kosher dining.', status:'available', icon:'Pizza', priority:'high' },
  { id:'bop-017', name:'Judaica / Gift Shop', category:'Retail', description:'Judaica items, gifts, books, holiday supplies, and specialty items for the community.', status:'available', icon:'Gift', priority:'medium' },
  { id:'bop-018', name:'Fitness / Gym', category:'Recreation', description:'Fitness center with separate mens and womens hours or facilities. Exercise equipment, classes.', status:'available', icon:'Dumbbell', priority:'medium' },
];

// Services needed for the development
export interface ServiceOpportunity { id:string; name:string; category:string; description:string; status:'needed'|'covered'|'partial'; providers:string[]; icon:string; }

export const serviceOpportunities: ServiceOpportunity[] = [
  { id:'svc-001', name:'Electrician', category:'Construction & Trades', description:'Licensed electrician for residential and commercial electrical work, installations, and repairs.', status:'needed', providers:[], icon:'Zap' },
  { id:'svc-002', name:'Plumber', category:'Construction & Trades', description:'Licensed plumber for residential and commercial plumbing installations, repairs, and maintenance.', status:'needed', providers:[], icon:'Wrench' },
  { id:'svc-003', name:'HVAC Technician', category:'Construction & Trades', description:'Heating, ventilation, and air conditioning installation, repair, and maintenance services.', status:'needed', providers:[], icon:'Thermometer' },
  { id:'svc-004', name:'Landscaping & Lawn Care', category:'Property Maintenance', description:'Commercial and residential landscaping, irrigation, mowing, and grounds maintenance.', status:'covered', providers:['Sunshine Landscaping LLC'], icon:'TreePine' },
  { id:'svc-005', name:'Pest Control', category:'Property Maintenance', description:'Residential and commercial pest control, termite treatment, and prevention services.', status:'needed', providers:[], icon:'Bug' },
  { id:'svc-006', name:'Pool Service & Maintenance', category:'Property Maintenance', description:'Swimming pool cleaning, chemical balancing, equipment repair, and maintenance.', status:'needed', providers:[], icon:'Waves' },
  { id:'svc-007', name:'Roofing', category:'Construction & Trades', description:'Roof installation, repair, and maintenance for residential and commercial buildings.', status:'needed', providers:[], icon:'Home' },
  { id:'svc-008', name:'Painting', category:'Construction & Trades', description:'Interior and exterior painting for residential and commercial properties.', status:'needed', providers:[], icon:'Paintbrush' },
  { id:'svc-009', name:'Moving & Delivery', category:'Logistics', description:'Local and long-distance moving, furniture delivery, and freight services.', status:'needed', providers:[], icon:'Truck' },
  { id:'svc-010', name:'Shipping & Courier', category:'Logistics', description:'Package shipping, courier services, mailbox rental, and notary services.', status:'needed', providers:[], icon:'Package' },
  { id:'svc-011', name:'IT / Computer Repair', category:'Technology', description:'Computer repair, IT support, networking, security cameras, and smart home installations.', status:'covered', providers:['TechConnect Solutions'], icon:'Monitor' },
  { id:'svc-012', name:'Cleaning Services', category:'Property Maintenance', description:'Residential and commercial cleaning, move-in/move-out cleaning, and janitorial services.', status:'covered', providers:['Florida Commercial Cleaning'], icon:'Sparkles' },
  { id:'svc-013', name:'Locksmith', category:'Security', description:'Lock installation, rekeying, emergency lockout services, and security system installation.', status:'needed', providers:[], icon:'KeyRound' },
  { id:'svc-014', name:'Catering / Event Services', category:'Food & Beverage', description:'Kosher catering for events, simchas, and community gatherings. Event planning and rentals.', status:'needed', providers:[], icon:'ChefHat' },
  { id:'svc-015', name:'Auto Mechanic', category:'Automotive', description:'General auto repair, oil changes, brake service, tire service, and inspections.', status:'needed', providers:[], icon:'Car' },
  { id:'svc-016', name:'General Contractor', category:'Construction & Trades', description:'Licensed general contractor for renovations, additions, and new construction projects.', status:'partial', providers:['One contractor available, more needed'], icon:'HardHat' },
];

export const mockBusinesses: Business[] = [
  { id:'biz-001', name:'Lakefront Supermarket', slug:'lakefront-supermarket', description:'Full-service grocery store serving the Lakefront community.', category:'food-beverage', contactName:'David Greenfeld', contactEmail:'market@lakefrontestatesfl.com', contactPhone:'863-333-9401', status:'active', isPublic:true, tags:['grocery','kosher','bakery'] },
  { id:'biz-002', name:'Lakefront Medical Center', slug:'lakefront-medical-center', description:'Comprehensive primary care and urgent care facility.', category:'healthcare', contactName:'Dr. Sarah Miller', contactEmail:'medical@lakefrontestatesfl.com', status:'active', isPublic:true, tags:['medical','primary-care'] },
  { id:'biz-003', name:'Lakefront Learning Academy', slug:'lakefront-learning-academy', description:'Educational institution for children of all ages.', category:'education', contactName:'Rabbi Moshe Katz', contactEmail:'education@lakefrontestatesfl.com', status:'active', isPublic:true, tags:['education','school'] },
  { id:'biz-004', name:'Lakefront Professional Plaza', slug:'lakefront-professional-plaza', description:'Multi-tenant office complex for professional services.', category:'professional-services', contactName:'Mark Thompson', contactEmail:'offices@lakefrontestatesfl.com', status:'approved', isPublic:true, tags:['office','professional'] },
];

export const mockProviders: ServiceProvider[] = [
  { id:'prov-001', name:'Sunshine Landscaping LLC', description:'Commercial and residential landscaping.', category:'landscaping', contactName:'Carlos Rodriguez', contactEmail:'carlos@sunshinelandscaping.com', contactPhone:'863-555-0101', status:'active', isPublic:true },
  { id:'prov-002', name:'TechConnect Solutions', description:'IT support, networking, and security systems.', category:'technology', contactName:'Mike Chen', contactEmail:'mike@techconnect.com', status:'active', isPublic:true },
  { id:'prov-003', name:'Florida Commercial Cleaning', description:'Professional cleaning services for commercial spaces.', category:'cleaning', contactName:'Ana Perez', contactEmail:'ana@flcleaningpro.com', status:'active', isPublic:true },
];

export const mockSpaces: CommercialSpace[] = [
  { id:'space-001', name:'Retail Suite A-101', slug:'retail-suite-a-101', description:'Prime ground-floor retail space. High visibility, move-in ready.', type:'retail', sqft:1200, monthlyRate:2400, building:'Shopping Plaza A', floor:'Ground', unit:'A-101', amenities:['Storefront','Parking','Loading dock','HVAC'], status:'available', isPublic:true },
  { id:'space-002', name:'Office Suite B-204', slug:'office-suite-b-204', description:'Professional office with reception area and conference room.', type:'office', sqft:850, monthlyRate:1700, building:'Professional Plaza B', floor:'2nd', unit:'B-204', amenities:['Conference room','Kitchenette','Parking','Fiber internet'], status:'available', isPublic:true },
  { id:'space-003', name:'Retail Suite A-105', slug:'retail-suite-a-105', description:'Corner retail unit with dual entrances. Ideal for restaurant.', type:'retail', sqft:2200, monthlyRate:4400, building:'Shopping Plaza A', floor:'Ground', unit:'A-105', amenities:['Corner location','Dual entrance','Grease trap','Parking'], status:'available', isPublic:true },
  { id:'space-004', name:'Warehouse Unit W-01', slug:'warehouse-unit-w-01', description:'Light industrial/warehouse space with drive-in access.', type:'warehouse', sqft:3500, monthlyRate:3500, building:'Warehouse Complex', floor:'Ground', unit:'W-01', amenities:['Drive-in bay','16ft ceiling','3-phase power','Office area'], status:'available', isPublic:true },
];

export const mockApplications: JobApplication[] = [
  { id:'app-001', jobId:'job-001', jobTitle:'Community Center Manager', contactId:'c-001', applicantName:'Rebecca Johnson', applicantEmail:'rebecca@email.com', applicantPhone:'561-555-0111', status:'reviewing', dateApplied:'2026-03-12' },
  { id:'app-002', jobId:'job-001', jobTitle:'Community Center Manager', contactId:'c-002', applicantName:'Michael Davis', applicantEmail:'mdavis@email.com', status:'interview', dateApplied:'2026-03-11' },
  { id:'app-003', jobId:'job-003', jobTitle:'Medical Office Receptionist', contactId:'c-003', applicantName:'Sarah Kim', applicantEmail:'skim@email.com', applicantPhone:'772-555-0222', status:'new', dateApplied:'2026-03-18' },
  { id:'app-004', jobId:'job-005', jobTitle:'Marketing Coordinator', contactId:'c-004', applicantName:'James Wilson', applicantEmail:'jwilson@email.com', status:'new', dateApplied:'2026-03-19' },
];

export const mockInvestors: InvestorLead[] = [
  { id:'inv-001', contactName:'Robert Sterling', contactEmail:'rsterling@capitalgroup.com', contactPhone:'212-555-0300', companyName:'Sterling Capital Group', investmentInterest:'Commercial real estate', investmentRange:'$500K - $2M', status:'due-diligence', contactId:'c-010', dateSubmitted:'2026-02-15' },
  { id:'inv-002', contactName:'Lisa Chen', contactEmail:'lchen@investcorp.com', companyName:'Pacific Investment Corp', investmentInterest:'Mixed-use development', investmentRange:'$1M - $5M', status:'meeting', contactId:'c-011', dateSubmitted:'2026-03-01' },
];
