'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Save, Eye } from 'lucide-react';
export default function NewJobPage() {
  const [form, setForm] = useState({ title:'', description:'', requirements:'', benefits:'', employerName:'', category:'', type:'full-time', workMode:'on-site', location:'Okeechobee, FL', salaryMin:'', salaryMax:'', salaryType:'annual', status:'draft', isPublic:false });
  function handleSubmit(e: React.FormEvent) { e.preventDefault(); console.log('Creating job:', form); }
  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex items-center justify-between"><div className="flex items-center gap-3"><Link href="/portal/jobs" className="p-2 rounded-lg hover:bg-gray-100 transition-colors"><ArrowLeft className="w-4 h-4 text-gray-500" /></Link><div><h1 className="text-2xl font-display font-bold text-brand-text">New Job Posting</h1><p className="text-sm font-body text-brand-muted mt-0.5">Create a new job listing.</p></div></div><div className="flex items-center gap-2"><button className="flex items-center gap-1.5 px-4 py-2 border border-gray-300 rounded-lg text-sm font-body font-medium text-brand-text/70 hover:bg-gray-50 transition-colors"><Eye className="w-4 h-4" /> Preview</button><button onClick={handleSubmit} className="btn-portal"><Save className="w-4 h-4 mr-1.5" /> Save</button></div></div>
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="card-portal p-6 space-y-5"><h2 className="text-base font-display font-semibold text-brand-text">Basic Information</h2>
          <div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Job Title *</label><input required type="text" value={form.title} onChange={e => setForm({...form, title:e.target.value})} className="input-portal" placeholder="e.g., Community Center Manager" /></div>
          <div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Employer *</label><input required type="text" value={form.employerName} onChange={e => setForm({...form, employerName:e.target.value})} className="input-portal" /></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Category *</label><input required type="text" value={form.category} onChange={e => setForm({...form, category:e.target.value})} className="input-portal" placeholder="e.g., Healthcare, Retail" /></div></div>
          <div className="grid sm:grid-cols-3 gap-4"><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Job Type</label><select value={form.type} onChange={e => setForm({...form, type:e.target.value})} className="input-portal"><option value="full-time">Full-Time</option><option value="part-time">Part-Time</option><option value="contract">Contract</option><option value="seasonal">Seasonal</option><option value="internship">Internship</option></select></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Work Mode</label><select value={form.workMode} onChange={e => setForm({...form, workMode:e.target.value})} className="input-portal"><option value="on-site">On-site</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option></select></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Location</label><input type="text" value={form.location} onChange={e => setForm({...form, location:e.target.value})} className="input-portal" /></div></div>
        </div>
        <div className="card-portal p-6 space-y-5"><h2 className="text-base font-display font-semibold text-brand-text">Details</h2>
          <div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Description *</label><textarea required rows={6} value={form.description} onChange={e => setForm({...form, description:e.target.value})} className="input-portal" placeholder="Full job description..." /></div>
          <div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Requirements</label><textarea rows={3} value={form.requirements} onChange={e => setForm({...form, requirements:e.target.value})} className="input-portal" placeholder="Skills, qualifications..." /></div>
          <div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Benefits</label><textarea rows={3} value={form.benefits} onChange={e => setForm({...form, benefits:e.target.value})} className="input-portal" placeholder="Compensation, perks..." /></div>
        </div>
        <div className="card-portal p-6 space-y-5"><h2 className="text-base font-display font-semibold text-brand-text">Compensation</h2>
          <div className="grid sm:grid-cols-3 gap-4"><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Minimum</label><input type="number" value={form.salaryMin} onChange={e => setForm({...form, salaryMin:e.target.value})} className="input-portal" placeholder="0" /></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Maximum</label><input type="number" value={form.salaryMax} onChange={e => setForm({...form, salaryMax:e.target.value})} className="input-portal" placeholder="0" /></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Pay Type</label><select value={form.salaryType} onChange={e => setForm({...form, salaryType:e.target.value})} className="input-portal"><option value="annual">Annual</option><option value="hourly">Hourly</option></select></div></div>
        </div>
        <div className="card-portal p-6 space-y-5"><h2 className="text-base font-display font-semibold text-brand-text">Publishing</h2>
          <div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Status</label><select value={form.status} onChange={e => setForm({...form, status:e.target.value})} className="input-portal"><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option></select></div><div className="flex items-center gap-3 pt-5"><label className="relative inline-flex items-center cursor-pointer"><input type="checkbox" checked={form.isPublic} onChange={e => setForm({...form, isPublic:e.target.checked})} className="sr-only peer" /><div className="w-11 h-6 bg-gray-200 peer-focus:ring-2 peer-focus:ring-portal-accent/30 rounded-full peer peer-checked:after:translate-x-full peer-checked:bg-portal-accent after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all" /></label><span className="text-sm font-body text-brand-text">Visible on public website</span></div></div>
        </div>
        <div className="flex items-center gap-3"><button type="submit" className="btn-portal"><Save className="w-4 h-4 mr-1.5" /> Save Job</button><Link href="/portal/jobs" className="px-5 py-2.5 text-sm font-body font-medium text-brand-muted hover:text-brand-text transition-colors">Cancel</Link></div>
      </form>
    </div>
  );
}
