'use client';
import { useState } from 'react';
import { Warehouse, Send, CheckCircle } from 'lucide-react';
import { ScrollReveal } from '@/components/public/ScrollReveal';

// ITEM 29: Space rental application page
export default function SpaceApplyPage() {
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState({ businessName: '', contactName: '', email: '', phone: '', address: '', spaceType: '', sqftNeeded: '', budget: '', description: '', moveInDate: '' });

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault(); setSubmitting(true);
    await fetch('/api/public/apply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ applicant_name: form.businessName, applicant_email: form.email, applicant_phone: form.phone, address: form.address, application_type: 'space_rental', cover_letter: `Business: ${form.businessName}\nContact: ${form.contactName}\nSpace Type: ${form.spaceType}\nSqft Needed: ${form.sqftNeeded}\nBudget: ${form.budget}\nMove-in: ${form.moveInDate}\n\n${form.description}`, status: 'submitted' }) });
    setSubmitted(true); setSubmitting(false);
  }

  return (
    <div>
      <div className="gradient-forest relative overflow-hidden"><div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'url(https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600)', backgroundSize: 'cover', backgroundPosition: 'center' }} /><div className="max-container section-padding py-20 relative z-10"><ScrollReveal><div className="text-center"><p className="text-xs tracking-[0.3em] uppercase mb-3 font-body font-semibold" style={{ color: '#C9B97A' }}>Commercial Spaces</p><h1 className="font-display text-3xl lg:text-4xl font-bold text-white">Rent a Space</h1><div className="w-12 h-[2px] mx-auto mt-4 mb-4" style={{ backgroundColor: '#C9B97A' }} /><p className="text-base text-white/50 font-body max-w-lg mx-auto">Apply to rent commercial or retail space at Lakefront Estates.</p></div></ScrollReveal></div></div>
      <div className="bg-[#FAFAF7] py-16"><div className="max-container section-padding max-w-2xl mx-auto">
        {submitted ? (<div className="bg-green-50 border border-green-200 rounded-xl p-8 text-center"><CheckCircle className="w-12 h-12 text-green-500 mx-auto mb-4" /><h2 className="font-display text-xl font-semibold text-green-800 mb-2">Application Submitted!</h2><p className="text-sm text-green-600 font-body">We'll review your space rental application shortly.</p></div>
        ) : (<div className="bg-white rounded-xl border border-gray-100 p-8"><div className="flex items-center gap-3 mb-6"><Warehouse className="w-8 h-8 text-brand-forest" /><div><h2 className="font-display text-lg font-semibold" style={{ color: '#2C3E2D' }}>Space Rental Application</h2><p className="text-xs font-body text-gray-400">Tell us what space you need</p></div></div>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Business Name *</label><input required value={form.businessName} onChange={e => setForm({...form, businessName: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" /></div><div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Contact Name *</label><input required value={form.contactName} onChange={e => setForm({...form, contactName: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" /></div><div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Email *</label><input required type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" /></div><div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Phone</label><input value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" /></div></div>
            <div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Current Business Address</label><input value={form.address} onChange={e => setForm({...form, address: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" /></div>
            <div className="grid sm:grid-cols-3 gap-4"><div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Space Type *</label><select required value={form.spaceType} onChange={e => setForm({...form, spaceType: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]"><option value="">Select...</option><option>Retail</option><option>Office</option><option>Restaurant</option><option>Medical</option><option>Warehouse</option><option>Mixed Use</option></select></div><div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Sqft Needed</label><input value={form.sqftNeeded} onChange={e => setForm({...form, sqftNeeded: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" placeholder="e.g. 1,200" /></div><div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Monthly Budget</label><input value={form.budget} onChange={e => setForm({...form, budget: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" placeholder="e.g. $2,500" /></div></div>
            <div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">What will you use the space for? *</label><textarea required rows={3} value={form.description} onChange={e => setForm({...form, description: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A] resize-none" /></div>
            <div><label className="block text-xs font-body font-medium text-gray-500 mb-1 uppercase">Desired Move-in Date</label><input type="date" value={form.moveInDate} onChange={e => setForm({...form, moveInDate: e.target.value})} className="w-full px-4 py-2.5 border border-gray-200 rounded-lg text-sm font-body focus:outline-none focus:border-[#C9B97A]" /></div>
            <button type="submit" disabled={submitting} className="inline-flex items-center gap-2 px-6 py-3 rounded-full text-sm font-body font-semibold text-white transition-all hover:shadow-lg disabled:opacity-50" style={{ backgroundColor: '#C9B97A' }}>{submitting ? 'Submitting...' : 'Submit Application'}<Send className="w-4 h-4" /></button>
          </form></div>)}
      </div></div>
    </div>
  );
}
