'use client';
import { useState } from 'react';
import { Phone, Mail, MapPin, CheckCircle, Send } from 'lucide-react';
export default function ContactPage() {
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ firstName:'', lastName:'', email:'', phone:'', subject:'', message:'' });
  function handleSubmit(e: React.FormEvent) { e.preventDefault(); setSubmitted(true); }
  return (<>
    <section className="gradient-forest py-16 lg:py-24"><div className="max-container section-padding"><p className="text-brand-gold font-body font-semibold text-xs tracking-[0.2em] uppercase mb-4">Contact</p><h1 className="font-display text-3xl lg:text-5xl font-bold text-white mb-4">Get in Touch</h1><p className="text-lg text-white/60 font-body max-w-xl">Have questions? We&apos;d love to hear from you.</p></div></section>
    <section className="py-16 lg:py-24 bg-brand-warm"><div className="max-container section-padding"><div className="grid lg:grid-cols-3 gap-12">
      <div className="space-y-6"><h2 className="font-display text-2xl font-bold text-brand-forest mb-2">Contact Information</h2><p className="text-sm text-brand-muted font-body">Reach out to our economic development team.</p><div className="space-y-4 pt-4"><a href="tel:+18633339400" className="flex items-center gap-3 group"><div className="w-10 h-10 rounded-sm bg-brand-sage/10 flex items-center justify-center shrink-0 group-hover:bg-brand-sage/20 transition-colors"><Phone className="w-5 h-5 text-brand-sage" /></div><div><p className="text-xs font-body text-brand-muted uppercase tracking-wider">Phone</p><p className="text-sm font-body font-medium text-brand-text">863.333.9400</p></div></a><a href="mailto:info@lakefrontestatesfl.com" className="flex items-center gap-3 group"><div className="w-10 h-10 rounded-sm bg-brand-sage/10 flex items-center justify-center shrink-0 group-hover:bg-brand-sage/20 transition-colors"><Mail className="w-5 h-5 text-brand-sage" /></div><div><p className="text-xs font-body text-brand-muted uppercase tracking-wider">Email</p><p className="text-sm font-body font-medium text-brand-text">info@lakefrontestatesfl.com</p></div></a><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-sm bg-brand-sage/10 flex items-center justify-center shrink-0"><MapPin className="w-5 h-5 text-brand-sage" /></div><div><p className="text-xs font-body text-brand-muted uppercase tracking-wider">Location</p><p className="text-sm font-body font-medium text-brand-text">Okeechobee, FL 34974</p></div></div></div></div>
      <div className="lg:col-span-2">{submitted ? (<div className="text-center py-16 bg-white rounded-sm border border-gray-100"><div className="w-16 h-16 rounded-full bg-brand-sage/10 flex items-center justify-center mx-auto mb-6"><CheckCircle className="w-8 h-8 text-brand-sage" /></div><h2 className="font-display text-2xl font-bold text-brand-forest mb-3">Message Sent</h2><p className="text-brand-muted font-body">Thank you! We&apos;ll get back to you shortly.</p></div>) : (<form onSubmit={handleSubmit} className="bg-white rounded-sm border border-gray-100 p-8 space-y-5"><div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">First Name *</label><input required type="text" value={form.firstName} onChange={e => setForm({...form, firstName: e.target.value})} className="input-field" /></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Last Name *</label><input required type="text" value={form.lastName} onChange={e => setForm({...form, lastName: e.target.value})} className="input-field" /></div></div><div className="grid sm:grid-cols-2 gap-4"><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Email *</label><input required type="email" value={form.email} onChange={e => setForm({...form, email: e.target.value})} className="input-field" /></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Phone</label><input type="tel" value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} className="input-field" /></div></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Subject *</label><select required value={form.subject} onChange={e => setForm({...form, subject: e.target.value})} className="input-field"><option value="">Select a topic</option><option value="general">General Inquiry</option><option value="jobs">Employment</option><option value="business">Business</option><option value="commercial">Commercial Space</option><option value="investment">Investment</option><option value="other">Other</option></select></div><div><label className="block text-xs font-body font-medium text-brand-muted mb-1.5 uppercase tracking-wider">Message *</label><textarea required rows={5} value={form.message} onChange={e => setForm({...form, message: e.target.value})} className="input-field" placeholder="How can we help?" /></div><button type="submit" className="btn-primary"><Send className="w-4 h-4 mr-2" /> Send Message</button></form>)}</div>
    </div></div></section>
  </>);
}
